### ISSUE TITLE
('listen' was unexpected)

### ISSUE THREAD

**Issue by fahdmirza** [katanemo/arch#221] opened 2024-10-24 21:36 UTC
Hi,
 Followed your quickstart and on Ubuntu 22.04, got this error :

(ai) Ubuntu@0056-kci-prxmx10054:~/arch$ archgw up config.yaml
Validating /home/Ubuntu/arch/config.yaml
Error validating arch_config file: /home/Ubuntu/arch/config.yaml, error: Additional properties are not allowed ('listen' was unexpected)
Exiting archgw up: Additional properties are not allowed ('listen' was unexpected)

regards,

**Comment by salmanap** [comment] 2024-10-24 21:46
Hey - sorry for the poor user experience. The arch_config.yaml should have "listener" as a property. I would encourage you to have a quick look at our example demos: https://github.com/katanemo/arch/tree/main/demos/hr_agent for more guidance on how to build your configuration file.

**Comment by salmanap** [comment] 2024-10-24 21:48
Also for the state to work correctly, the chatbot_ui has a reference implementation on what Arch needs to ensure more accurate resolution of prompt-targets. We are making this simpler, but if you get started with our demos it might be helpful.

**Comment by salmanap** [comment] 2024-10-24 21:57
btw, we just fixed the README https://github.com/katanemo/arch/pull/223 because it had an older reference to "listen". Sorry about that.

**Comment by fahdmirza** [comment] 2024-10-24 22:13
All good, thanks for prompt and helpful replies. 

I am just looking to see how it works so that I could review it. I will get it another try .

**Comment by fahdmirza** [comment] 2024-10-24 22:23
Tried again and still unable to run it with that config file. Also tried with the docker demo but in vain. Quickstart or read me doesn't really mention how to run this demo or anything simple. The demo link you shared also mentions slack. I don't have slack and for starter demo, all we want is a simple setup.

I just wanted to review this tool for my channel with a simple working demo after installation. I will revisit this in future. 

Thanks for the help again. 
regards,

**Comment by adilhafeez** [comment] 2024-10-24 22:29
> The demo link you shared also mentions slack.

Slack key is not required for demo. In the absence of key it would just print the slack message on console.

> Also tried with the docker demo but in vain

Can you pls post logs?

> I just wanted to review this tool for my channel with a simple working demo after installation

That would be amazing ❤️

**Comment by fahdmirza** [comment] 2024-10-24 23:13
I have started docker compose up, which URL to access in browser at local host? http://localhost:80 or 8080 doesnt work . 


(ai) Ubuntu@0056-kci-prxmx10054:~/arch/demos/hr_agent$ docker compose up
[+] Building 72.2s (26/26) FINISHED                                                          docker:default
 => [api_server internal] load build definition from Dockerfile                                        0.1s
 => => transferring dockerfile: 434B                                                                   0.0s
 => [chatbot_ui internal] load build definition from Dockerfile                                        0.1s
 => => transferring dockerfile: 344B                                                                   0.0s
 => [api_server internal] load metadata for docker.io/library/python:3.10                              0.9s
 => [api_server internal] load metadata for docker.io/library/python:3.10-slim                         1.0s
 => [chatbot_ui internal] load .dockerignore                                                           0.0s
 => => transferring context: 2B                                                                        0.0s
 => [api_server internal] load .dockerignore                                                           0.0s
 => => transferring context: 2B                                                                        0.0s
 => [api_server base 1/1] FROM docker.io/library/python:3.10@sha256:fd0fa50d997eb56ce560c6e5ca6a1f5c  18.3s
 => => resolve docker.io/library/python:3.10@sha256:fd0fa50d997eb56ce560c6e5ca6a1f5cf8fdff87572a16ac0  0.0s
 => => sha256:fd0fa50d997eb56ce560c6e5ca6a1f5cf8fdff87572a16ac07fb1f5ca01eb608 9.08kB / 9.08kB         0.0s
 => => sha256:3b9d6bd35f8ef7d0697e7b08d1f5c781e488d3c8d1df3338b03bc22be44514d6 2.33kB / 2.33kB         0.0s
 => => sha256:9ec1cdbafe6e73e1c44c39ee914db2553cc367cbfdf215429bac3133b2c11778 6.32kB / 6.32kB         0.0s
 => => sha256:7d98d813d54f6207a57721008a4081378343ad8f1b2db66c121406019171805b 49.56MB / 49.56MB       0.8s
 => => sha256:da802df85c965baeca9d39869f9e2cbb3dc844d4627f413bfbb2f2c3d6055988 24.05MB / 24.05MB       1.1s
 => => sha256:7aadc5092c3b7a865666b14bef3d4d038282b19b124542f1a158c98ea8c1ed1b 64.39MB / 64.39MB       1.3s
 => => sha256:ad1c7cfc347f5c86fc2678b58f6a8fb6c6003471405760532fc3240b9eb1b343 211.27MB / 211.27MB     4.9s
 => => extracting sha256:7d98d813d54f6207a57721008a4081378343ad8f1b2db66c121406019171805b              3.1s
 => => sha256:4d508a9407359de608ead2a7e385506c4cb830d0e6937bc10caabb98da682c7c 6.16MB / 6.16MB         1.2s
 => => sha256:60ed5086cc45cf232728d1d4f1d59871dbf5e98b2f622b2918d6ab45c88de5c8 21.38MB / 21.38MB       1.7s
 => => sha256:0a52f5c07e30cfc04c0209bdd45963b9b55d65e569d2bb91ab5cfe772ae63f87 250B / 250B             1.4s
 => => extracting sha256:da802df85c965baeca9d39869f9e2cbb3dc844d4627f413bfbb2f2c3d6055988              0.7s
 => => extracting sha256:7aadc5092c3b7a865666b14bef3d4d038282b19b124542f1a158c98ea8c1ed1b              3.0s
 => => extracting sha256:ad1c7cfc347f5c86fc2678b58f6a8fb6c6003471405760532fc3240b9eb1b343              8.1s
 => => extracting sha256:4d508a9407359de608ead2a7e385506c4cb830d0e6937bc10caabb98da682c7c              0.3s
 => => extracting sha256:60ed5086cc45cf232728d1d4f1d59871dbf5e98b2f622b2918d6ab45c88de5c8              0.9s
 => => extracting sha256:0a52f5c07e30cfc04c0209bdd45963b9b55d65e569d2bb91ab5cfe772ae63f87              0.0s
 => [chatbot_ui output 1/4] FROM docker.io/library/python:3.10-slim@sha256:eb9ca77b1a0ffbde84c1dc333b  4.6s
 => => resolve docker.io/library/python:3.10-slim@sha256:eb9ca77b1a0ffbde84c1dc333beb3490a2638813cc25  0.0s
 => => sha256:3e625a83fe8d3ea2a08e8752ea253145030a2ed42baf00582dbe129e7f79d392 5.45kB / 5.45kB         0.0s
 => => sha256:a480a496ba95a197d587aa1d9e0f545ca7dbd40495a4715342228db62b67c4ba 29.13MB / 29.13MB       0.5s
 => => sha256:9555349e83800c1a78e4b4bb23f7952a24688a79b633620b8125923a1bf3e3ad 3.51MB / 3.51MB         0.2s
 => => sha256:1c161e44b06b47575aa10197160213eb6643d4e081f57397d5cabbe41563ae51 15.64MB / 15.64MB       0.4s
 => => sha256:eb9ca77b1a0ffbde84c1dc333beb3490a2638813cc25a339f8575668855b9ff1 9.13kB / 9.13kB         0.0s
 => => sha256:e7d6ea327beabaeeb064aa3334a56ab0d99ca52e335abcbacf6b1af3fe543def 1.75kB / 1.75kB         0.0s
 => => sha256:417516d8bb61dd3aee6a1637ced8f895d4b96ae5e846498089492017767db731 249B / 249B             0.3s
 => => extracting sha256:a480a496ba95a197d587aa1d9e0f545ca7dbd40495a4715342228db62b67c4ba              1.9s
 => => extracting sha256:9555349e83800c1a78e4b4bb23f7952a24688a79b633620b8125923a1bf3e3ad              0.2s
 => => extracting sha256:1c161e44b06b47575aa10197160213eb6643d4e081f57397d5cabbe41563ae51              1.2s
 => => extracting sha256:417516d8bb61dd3aee6a1637ced8f895d4b96ae5e846498089492017767db731              0.0s
 => [api_server internal] load build context                                                           0.0s
 => => transferring context: 9.20kB                                                                    0.0s
 => [chatbot_ui internal] load build context                                                           0.0s
 => => transferring context: 9.07kB                                                                    0.0s
 => [chatbot_ui builder 1/5] WORKDIR /src                                                              1.2s
 => [api_server builder 2/5] COPY requirements.txt /src/                                               0.1s
 => [chatbot_ui builder 2/4] COPY requirements.txt /src/                                               0.1s
 => [chatbot_ui builder 3/4] RUN pip install --prefix=/runtime --force-reinstall -r requirements.txt  40.3s
 => [api_server builder 3/5] COPY workforce_data.json /src/                                            0.1s
 => [api_server builder 4/5] RUN pip install --prefix=/runtime --force-reinstall -r requirements.txt  23.2s
 => [api_server builder 5/5] COPY . /src                                                               0.1s
 => [api_server output 2/4] COPY --from=builder /runtime /usr/local                                    2.2s
 => [api_server output 3/4] COPY . /app                                                                0.1s
 => [api_server output 4/4] WORKDIR /app                                                               0.0s
 => [api_server] exporting to image                                                                    1.5s
 => => exporting layers                                                                                1.4s
 => => writing image sha256:197891cf46607c0211ef5da2f9e20ec785d1237eca7edff6d6bdd1790a28409d           0.0s
 => => naming to docker.io/library/hr_agent-api_server                                                 0.0s
 => [chatbot_ui builder 4/4] COPY . /src                                                               0.1s
 => [chatbot_ui output 2/4] COPY --from=builder /runtime /usr/local                                    3.8s
 => [chatbot_ui output 3/4] COPY /app /app                                                             0.0s
 => [chatbot_ui output 4/4] WORKDIR /app                                                               0.0s
 => [chatbot_ui] exporting to image                                                                    3.7s
 => => exporting layers                                                                                3.7s
 => => writing image sha256:f73319782f82a2ba018e76e7bceb6e378f504c6a6250967bdca8f2fd9171c2ad           0.0s
 => => naming to docker.io/library/hr_agent-chatbot_ui                                                 0.0s
[+] Running 1/3
 ✔ Network hr_agent_default         Created                                                            0.1s 
 ⠋ Container hr_agent-chatbot_ui-1  Created                                                            0.1s 
 ⠋ Container hr_agent-api_server-1  Created                                                            0.1s 
Attaching to api_server-1, chatbot_ui-1
api_server-1  | INFO:     Started server process [1]
api_server-1  | INFO:     Waiting for application startup.
api_server-1  | INFO:     Application startup complete.
api_server-1  | INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
chatbot_ui-1  | 2024-10-24 23:09:32,536 - INFO - CHAT_COMPLETION_ENDPOINT: http://host.docker.internal:10000/v1
chatbot_ui-1  | /usr/local/lib/python3.10/site-packages/gradio/components/chatbot.py:223: UserWarning: You have not specified a value for the `type` parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style 'role' and 'content' keys.
chatbot_ui-1  |   warnings.warn(
chatbot_ui-1  | 2024-10-24 23:09:33,004 - INFO - HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
chatbot_ui-1  | 2024-10-24 23:09:33,173 - INFO - HTTP Request: GET http://localhost:8080/gradio_api/startup-events "HTTP/1.1 200 OK"
chatbot_ui-1  | 2024-10-24 23:09:33,200 - INFO - HTTP Request: HEAD http://localhost:8080/ "HTTP/1.1 200 OK"

**Comment by adilhafeez** [comment] 2024-10-24 23:22
We map gradio client to hosts [18080](https://github.com/katanemo/arch/blob/main/demos/hr_agent/docker-compose.yaml#L17-L18)

**Comment by fahdmirza** [comment] 2024-10-24 23:29
ok, now its accessible in the browser. Could you please give me any sample prompts to test which would shine some light on this tool in this hr_agent?

**Comment by fahdmirza** [comment] 2024-10-24 23:33
And I tried this with few prompts and getting following errors :

`ents
chatbot_ui-1  |     response = await route_utils.call_process_api(
chatbot_ui-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
chatbot_ui-1  |     output = await app.get_blocks().process_api(
chatbot_ui-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 2018, in process_api
chatbot_ui-1  |     result = await self.call_function(
chatbot_ui-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1567, in call_function
chatbot_ui-1  |     prediction = await anyio.to_thread.run_sync(  # type: ignore
chatbot_ui-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
chatbot_ui-1  |     return await get_async_backend().run_sync_in_worker_thread(
chatbot_ui-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
chatbot_ui-1  |     return await future
chatbot_ui-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
chatbot_ui-1  |     result = context.run(func, *args)
chatbot_ui-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 846, in wrapper
chatbot_ui-1  |     response = f(*args, **kwargs)
chatbot_ui-1  |   File "/app/run.py", line 114, in chat
chatbot_ui-1  |     raise gr.Error("Error calling gateway API: {}".format(e.message))
chatbot_ui-1  | gradio.exceptions.Error: 'Error calling gateway API: Connection error.'

`

**Comment by salmanap** [comment] 2024-10-24 23:34
Try "give me workforce data for Asia" and follow up with "give me workforce data for Asia 30 days ago"

**Comment by salmanap** [comment] 2024-10-24 23:38
Hmmm that feels like an issue with a key not properly set for an LLM provider. I'll need to see the logs to be 100% sure. But can you confirm your Open AI API key is set in your local environment?

**Comment by fahdmirza** [comment] 2024-10-24 23:40
Yes it is. I will revisit this in the future when its more stable. Thanks for prompt replies though. Best of luck.

**Comment by salmanap** [comment] 2024-10-24 23:49
Deeply apologize for the poor experience. If you can drop the `archgw logs --debug --service archgw` to our discord server it would be greatly appreciated. We dont' want anyone to go through the experience you just went through. https://discord.gg/pGZf2gcwEc

I will close out this issue once you have published your logs to the discord channel so that we can debug today and make any emergency fixes if Ubuntu related or otherwise

**Comment by salmanap** [comment] 2024-10-24 23:55
One suspicion is that `Ubuntu@0056-kci-prxmx10054:~/arch/demos/hr_agent$ docker compose up` won't necessarily bring up archgw. Instead in the demos we give a shell script to run the demo via `sh run_demo.sh`. I see that the README for hr_agent is missing (unlike the other demos). Will fix

**Comment by salmanap** [comment] 2024-10-25 01:07
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/2e71aae5-d723-4bc9-8492-5935e5fbc5ba">

Please follow README of hr_agent. Just did a clean docker compose build. followed by `sh run_demo.sh` and attaching screenshot to show the user experience

**Comment by salmanap** [comment] 2024-10-25 01:17
But, of course, if this is failing for you on your local setup, we might have missed something obvious. Once again, super sorry about the poor first-run experience.

**Comment by salmanap** [comment] 2024-10-25 17:24
Closing out this issue for now, as I can't reproduce it. @fahdmirza would love to iterate with you over discord if you continue to find things not working.

**Closed by salmanap** 2024-10-25 17:24 UTC
